import { ResearchReport } from "./types/research";

export function exportToMarkdown(report: ResearchReport): string {
  const dateStr = new Date().toLocaleDateString();
  const timeStr = new Date().toLocaleTimeString();

  let md = `# Investment Research Report: ${report.company} (${report.ticker})\n`;
  md += `*Generated by InvestAI on ${dateStr} at ${timeStr}*\n\n`;

  md += `## 🎯 Verdict: ${report.verdict} (Score: ${report.finalScore ?? "N/A"})\n`;
  md += `**Risk Profile:** ${report.riskProfile?.toUpperCase() ?? "BALANCED"}\n`;
  md += `*Confidence: ${report.confidence?.score ?? 0}/100*\n\n`;

  if (report.agentDebate) {
    md += `## 🤖 AI Debate\n\n`;
    
    md += `### 🐂 Bull Case\n`;
    md += `${report.agentDebate.bull.summary}\n`;
    report.agentDebate.bull.arguments.forEach(arg => md += `- ${arg.claim}\n`);
    md += `\n`;

    md += `### 🐻 Bear Case\n`;
    md += `${report.agentDebate.bear.summary}\n`;
    report.agentDebate.bear.arguments.forEach(arg => md += `- ${arg.claim}\n`);
    md += `\n`;

    md += `### ⚠️ Risk Analysis\n`;
    md += `${report.agentDebate.risk.summary}\n`;
    report.agentDebate.risk.concerns.forEach(flag => md += `- ${flag}\n`);
    md += `\n`;
  }

  if (report.scoreBreakdown) {
    md += `## 📊 Score Breakdown\n`;
    report.scoreBreakdown.categoryScores.forEach(s => {
      md += `- **${s.category}:** ${s.rawScore}/100 (Weight: ${s.weight})\n`;
    });
    md += `\n`;
  }

  if (report.evidence && report.evidence.length > 0) {
    md += `## 🔎 Source-Backed Evidence\n`;
    md += `| Title | Metric | Value | Source |\n`;
    md += `|---|---|---|---|\n`;
    report.evidence.forEach(e => {
      md += `| ${e.title} | ${e.relatedMetric ?? "N/A"} | ${e.value ?? "N/A"} | ${e.source} |\n`;
    });
    md += `\n`;
  }

  md += `---\n\n`;
  md += `**Disclaimer:** This tool is for educational research only and does not provide financial advice. Always do your own research or consult a qualified financial advisor before investing.\n`;

  return md;
}

export function downloadMarkdown(report: ResearchReport) {
  const md = exportToMarkdown(report);
  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${report.ticker}-research-report.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
